[package]
name = "lissajous-macros"
version = "0.10.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Procedural macros for the Lissajous notebook library."
authors = ["Jan-Paul Bultmann <jp@bultmann.eu>"]
documentation = "https://docs.rs/lissajous-macros"
homepage = "https://lissajous.science"
repository = "https://github.com/erlkonig-ai/lissajous"

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "3"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
